Install compiler in CI container
Seeing in CI for test suite:

       error: linker `cc` not found

Since the test-suite is running in container pandoc/ubuntu-latex,
which likely is missing the build-essential package (cc, make,
autoconf)